### PR TITLE
Fix for https://github.com/aeagle/react-spaces/issues/49

### PR DESCRIPTION
**Pull request by thekapadia**
Hi @aeagle - our team investigated https://github.com/aeagle/react-spaces/issues/49 - and we found it to be a problem when `resizable={true}` and `scrollable={true}` - both are enabled.

This change in the `Space.tsx` file helped fix it. Please review.

_Note: Please ignore the whitespaces in the diff._

### CODE REVIEW

**Comment by thekapadia** [comment]
@aeagle Any thoughts on this?

**Comment by thekapadia** [comment]
Hi @aeagle - did you get a chance to look into this PR?

**Comment by aeagle** [comment]
Hi @thekapadia. My concern with the PR is that it reverses my effort to reduce the markup created by the spaces. The only scenario at the moment where an inner/outer element is required is when a space is resizable and scrollable to properly position the resize handle. At the moment, the change applied by this PR will generate an inner/outer element for all spaces. I am going to see if there is a way to position the resize handle in a scrollable space without requiring the inner/outer element as that would be the ideal solution.

**Comment by thekapadia** [comment]
Sure @aeagle, your concern is reasonable.

**Pull request closed without merging**
